import 'package:flutter/material.dart';
import 'package:mpay_app/theme/enhanced_theme.dart';

/// A class that provides localization support for the application
class AppLocalizations {
  final Locale locale;
  
  AppLocalizations(this.locale);
  
  /// Helper method to get current instance from context
  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }
  
  /// Delegate for creating AppLocalizations instances
  static const LocalizationsDelegate<AppLocalizations> delegate = _AppLocalizationsDelegate();
  
  /// Supported locales
  static const List<Locale> supportedLocales = [
    Locale('ar'), // Arabic
    Locale('en'), // English
  ];
  
  /// Map of localized values for Arabic
  static const Map<String, String> _localizedValuesAr = {
    // General
    'app_name': 'MPay Plus',
    'ok': 'موافق',
    'cancel': 'إلغاء',
    'save': 'حفظ',
    'delete': 'حذف',
    'edit': 'تعديل',
    'close': 'إغلاق',
    'back': 'رجوع',
    'next': 'التالي',
    'previous': 'السابق',
    'done': 'تم',
    'loading': 'جاري التحميل...',
    'error': 'خطأ',
    'success': 'نجاح',
    'warning': 'تحذير',
    'info': 'معلومات',
    'retry': 'إعادة المحاولة',
    'no_data': 'لا توجد بيانات',
    'search': 'بحث',
    'filter': 'تصفية',
    'sort': 'ترتيب',
    'settings': 'الإعدادات',
    'profile': 'الملف الشخصي',
    'logout': 'تسجيل الخروج',
    'login': 'تسجيل الدخول',
    'register': 'إنشاء حساب',
    'forgot_password': 'نسيت كلمة المرور؟',
    'reset_password': 'إعادة تعيين كلمة المرور',
    'change_password': 'تغيير كلمة المرور',
    'confirm_password': 'تأكيد كلمة المرور',
    'password': 'كلمة المرور',
    'email': 'البريد الإلكتروني',
    'phone': 'رقم الهاتف',
    'username': 'اسم المستخدم',
    'name': 'الاسم',
    'first_name': 'الاسم الأول',
    'last_name': 'الاسم الأخير',
    'address': 'العنوان',
    'city': 'المدينة',
    'country': 'الدولة',
    'postal_code': 'الرمز البريدي',
    'date': 'التاريخ',
    'time': 'الوقت',
    'amount': 'المبلغ',
    'currency': 'العملة',
    'description': 'الوصف',
    'category': 'الفئة',
    'status': 'الحالة',
    'type': 'النوع',
    'id': 'المعرف',
    'reference': 'المرجع',
    'details': 'التفاصيل',
    'summary': 'الملخص',
    'total': 'المجموع',
    'subtotal': 'المجموع الفرعي',
    'tax': 'الضريبة',
    'discount': 'الخصم',
    'fee': 'الرسوم',
    'balance': 'الرصيد',
    'available_balance': 'الرصيد المتاح',
    'pending_balance': 'الرصيد المعلق',
    'transaction': 'المعاملة',
    'transactions': 'المعاملات',
    'payment': 'الدفع',
    'payments': 'المدفوعات',
    'transfer': 'التحويل',
    'transfers': 'التحويلات',
    'deposit': 'الإيداع',
    'deposits': 'الإيداعات',
    'withdrawal': 'السحب',
    'withdrawals': 'السحوبات',
    'card': 'البطاقة',
    'cards': 'البطاقات',
    'account': 'الحساب',
    'accounts': 'الحسابات',
    'wallet': 'المحفظة',
    'wallets': 'المحافظ',
    'beneficiary': 'المستفيد',
    'beneficiaries': 'المستفيدين',
    'notification': 'الإشعار',
    'notifications': 'الإشعارات',
    'message': 'الرسالة',
    'messages': 'الرسائل',
    'support': 'الدعم',
    'help': 'المساعدة',
    'faq': 'الأسئلة الشائعة',
    'terms': 'الشروط والأحكام',
    'privacy': 'سياسة الخصوصية',
    'about': 'عن التطبيق',
    'contact': 'اتصل بنا',
    'version': 'الإصدار',
    'language': 'اللغة',
    'theme': 'السمة',
    'dark_mode': 'الوضع الداكن',
    'light_mode': 'الوضع الفاتح',
    'system_mode': 'وضع النظام',
    'accessibility': 'إمكانية الوصول',
    'security': 'الأمان',
    'biometrics': 'المصادقة البيومترية',
    'face_id': 'Face ID',
    'touch_id': 'Touch ID',
    'fingerprint': 'بصمة الإصبع',
    'pin': 'رمز PIN',
    'otp': 'رمز التحقق',
    'verification_code': 'رمز التحقق',
    'verification': 'التحقق',
    'confirm': 'تأكيد',
    'continue': 'متابعة',
    'skip': 'تخطي',
    'yes': 'نعم',
    'no': 'لا',
    'enable': 'تمكين',
    'disable': 'تعطيل',
    'enabled': 'مفعل',
    'disabled': 'معطل',
    'active': 'نشط',
    'inactive': 'غير نشط',
    'pending': 'معلق',
    'completed': 'مكتمل',
    'failed': 'فشل',
    'cancelled': 'ملغي',
    'rejected': 'مرفوض',
    'approved': 'موافق عليه',
    'processing': 'قيد المعالجة',
    'scheduled': 'مجدول',
    'recurring': 'متكرر',
    'one_time': 'مرة واحدة',
    'daily': 'يومي',
    'weekly': 'أسبوعي',
    'monthly': 'شهري',
    'yearly': 'سنوي',
    'today': 'اليوم',
    'yesterday': 'أمس',
    'tomorrow': 'غدًا',
    'this_week': 'هذا الأسبوع',
    'last_week': 'الأسبوع الماضي',
    'this_month': 'هذا الشهر',
    'last_month': 'الشهر الماضي',
    'this_year': 'هذا العام',
    'last_year': 'العام الماضي',
    'custom_range': 'نطاق مخصص',
    'start_date': 'تاريخ البدء',
    'end_date': 'تاريخ الانتهاء',
    'from': 'من',
    'to': 'إلى',
    'min': 'الحد الأدنى',
    'max': 'الحد الأقصى',
    'all': 'الكل',
    'none': 'لا شيء',
    'select_all': 'تحديد الكل',
    'select_none': 'إلغاء تحديد الكل',
    'select': 'تحديد',
    'selected': 'محدد',
    'choose': 'اختر',
    'choose_file': 'اختر ملف',
    'choose_image': 'اختر صورة',
    'upload': 'رفع',
    'download': 'تنزيل',
    'share': 'مشاركة',
    'copy': 'نسخ',
    'paste': 'لصق',
    'cut': 'قص',
    'undo': 'تراجع',
    'redo': 'إعادة',
    'add': 'إضافة',
    'remove': 'إزالة',
    'create': 'إنشاء',
    'update': 'تحديث',
    'refresh': 'تحديث',
    'reload': 'إعادة تحميل',
    'reset': 'إعادة ضبط',
    'clear': 'مسح',
    'clear_all': 'مسح الكل',
    'apply': 'تطبيق',
    'submit': 'إرسال',
    'send': 'إرسال',
    'receive': 'استلام',
    'request': 'طلب',
    'accept': 'قبول',
    'decline': 'رفض',
    'block': 'حظر',
    'unblock': 'إلغاء الحظر',
    'report': 'إبلاغ',
    'favorite': 'المفضلة',
    'unfavorite': 'إزالة من المفضلة',
    'bookmark': 'إضافة إشارة مرجعية',
    'unbookmark': 'إزالة الإشارة المرجعية',
    'like': 'إعجاب',
    'unlike': 'إلغاء الإعجاب',
    'follow': 'متابعة',
    'unfollow': 'إلغاء المتابعة',
    'more': 'المزيد',
    'less': 'أقل',
    'show_more': 'عرض المزيد',
    'show_less': 'عرض أقل',
    'expand': 'توسيع',
    'collapse': 'طي',
    'open': 'فتح',
    'close': 'إغلاق',
    'start': 'بدء',
    'stop': 'إيقاف',
    'pause': 'إيقاف مؤقت',
    'resume': 'استئناف',
    'play': 'تشغيل',
    'replay': 'إعادة تشغيل',
    'forward': 'تقديم',
    'backward': 'إرجاع',
    'first': 'الأول',
    'last': 'الأخير',
    'top': 'أعلى',
    'bottom': 'أسفل',
    'up': 'لأعلى',
    'down': 'لأسفل',
    'left': 'يسار',
    'right': 'يمين',
    'center': 'وسط',
    'horizontal': 'أفقي',
    'vertical': 'عمودي',
    'portrait': 'عمودي',
    'landscape': 'أفقي',
    'rotate': 'تدوير',
    'flip': 'قلب',
    'zoom_in': 'تكبير',
    'zoom_out': 'تصغير',
    'fit': 'ملائمة',
    'fill': 'ملء',
    'crop': 'اقتصاص',
    'resize': 'تغيير الحجم',
    'scale': 'تحجيم',
    'aspect_ratio': 'نسبة العرض إلى الارتفاع',
    'width': 'العرض',
    'height': 'الارتفاع',
    'size': 'الحجم',
    'small': 'صغير',
    'medium': 'متوسط',
    'large': 'كبير',
    'extra_small': 'صغير جدًا',
    'extra_large': 'كبير جدًا',
    'custom': 'مخصص',
    'default': 'افتراضي',
    'auto': 'تلقائي',
    'manual': 'يدوي',
    'on': 'تشغيل',
    'off': 'إيقاف',
    'high': 'مرتفع',
    'medium': 'متوسط',
    'low': 'منخفض',
    'normal': 'عادي',
    'fast': 'سريع',
    'slow': 'بطيء',
    'new': 'جديد',
    'old': 'قديم',
    'recent': 'حديث',
    'popular': 'شائع',
    'trending': 'رائج',
    'featured': 'مميز',
    'recommended': 'موصى به',
    'related': 'ذات صلة',
    'similar': 'مشابه',
    'other': 'آخر',
    'alternative': 'بديل',
    'main': 'رئيسي',
    'secondary': 'ثانوي',
    'tertiary': 'ثالث',
    'primary': 'أساسي',
    'accent': 'ثانوي',
    'background': 'خلفية',
    'foreground': 'أمامي',
    'transparent': 'شفاف',
    'opaque': 'معتم',
    'solid': 'صلب',
    'gradient': 'تدرج',
    'pattern': 'نمط',
    'texture': 'نسيج',
    'shadow': 'ظل',
    'blur': 'ضبابية',
    'sharp': 'حاد',
    'rounded': 'مستدير',
    'square': 'مربع',
    'circle': 'دائرة',
    'oval': 'بيضاوي',
    'rectangle': 'مستطيل',
    'triangle': 'مثلث',
    'polygon': 'مضلع',
    'star': 'نجمة',
    'heart': 'قلب',
    'arrow': 'سهم',
    'line': 'خط',
    'curve': 'منحنى',
    'path': 'مسار',
    'shape': 'شكل',
    'icon': 'أيقونة',
    'image': 'صورة',
    'video': 'فيديو',
    'audio': 'صوت',
    'file': 'ملف',
    'folder': 'مجلد',
    'document': 'مستند',
    'text': 'نص',
    'number': 'رقم',
    'boolean': 'منطقي',
    'date': 'تاريخ',
    'time': 'وقت',
    'datetime': 'تاريخ ووقت',
    'duration': 'المدة',
    'interval': 'الفاصل',
    'period': 'الفترة',
    'frequency': 'التكرار',
    'rate': 'المعدل',
    'speed': 'السرعة',
    'velocity': 'السرعة المتجهة',
    'acceleration': 'التسارع',
    'force': 'القوة',
    'pressure': 'الضغط',
    'temperature': 'درجة الحرارة',
    'volume': 'الحجم',
    'area': 'المساحة',
    'length': 'الطول',
    'distance': 'المسافة',
    'weight': 'الوزن',
    'mass': 'الكتلة',
    'density': 'الكثافة',
    'energy': 'الطاقة',
    'power': 'القدرة',
    'voltage': 'الجهد',
    'current': 'التيار',
    'resistance': 'المقاومة',
    'capacity': 'السعة',
    'charge': 'الشحنة',
    'frequency': 'التردد',
    'wavelength': 'الطول الموجي',
    'amplitude': 'السعة',
    'intensity': 'الشدة',
    'luminosity': 'السطوع',
    'brightness': 'الإضاءة',
    'contrast': 'التباين',
    'saturation': 'التشبع',
    'hue': 'اللون',
    'opacity': 'العتامة',
    'transparency': 'الشفافية',
    'alpha': 'ألفا',
    'beta': 'بيتا',
    'gamma': 'جاما',
    'delta': 'دلتا',
    'epsilon': 'إبسيلون',
    'zeta': 'زيتا',
    'eta': 'إيتا',
    'theta': 'ثيتا',
    'iota': 'يوتا',
    'kappa': 'كابا',
    'lambda': 'لامدا',
    'mu': 'مو',
    'nu': 'نو',
    'xi': 'كسي',
    'omicron': 'أوميكرون',
    'pi': 'باي',
    'rho': 'رو',
    'sigma': 'سيجما',
    'tau': 'تاو',
    'upsilon': 'أبسيلون',
    'phi': 'فاي',
    'chi': 'كاي',
    'psi': 'سي',
    'omega': 'أوميجا',
    
    // App specific
    'home': 'الرئيسية',
    'dashboard': 'لوحة التحكم',
    'send_money': 'إرسال الأموال',
    'request_money': 'طلب الأموال',
    'scan_qr': 'مسح رمز QR',
    'pay_bills': 'دفع الفواتير',
    'top_up': 'شحن الرصيد',
    'cash_out': 'سحب النقود',
    'my_cards': 'بطاقاتي',
    'my_accounts': 'حساباتي',
    'my_wallets': 'محافظي',
    'my_beneficiaries': 'المستفيدين',
    'transaction_history': 'سجل المعاملات',
    'recent_transactions': 'المعاملات الأخيرة',
    'transaction_details': 'تفاصيل المعاملة',
    'payment_confirmation': 'تأكيد الدفع',
    'payment_successful': 'تم الدفع بنجاح',
    'payment_failed': 'فشل الدفع',
    'transfer_confirmation': 'تأكيد التحويل',
    'transfer_successful': 'تم التحويل بنجاح',
    'transfer_failed': 'فشل التحويل',
    'add_money': 'إضافة أموال',
    'withdraw_money': 'سحب أموال',
    'add_card': 'إضافة بطاقة',
    'add_account': 'إضافة حساب',
    'add_wallet': 'إضافة محفظة',
    'add_beneficiary': 'إضافة مستفيد',
    'edit_card': 'تعديل البطاقة',
    'edit_account': 'تعديل الحساب',
    'edit_wallet': 'تعديل المحفظة',
    'edit_beneficiary': 'تعديل المستفيد',
    'delete_card': 'حذف البطاقة',
    'delete_account': 'حذف الحساب',
    'delete_wallet': 'حذف المحفظة',
    'delete_beneficiary': 'حذف المستفيد',
    'card_details': 'تفاصيل البطاقة',
    'account_details': 'تفاصيل الحساب',
    'wallet_details': 'تفاصيل المحفظة',
    'beneficiary_details': 'تفاصيل المستفيد',
    'card_number': 'رقم البطاقة',
    'card_holder': 'حامل البطاقة',
    'expiry_date': 'تاريخ الانتهاء',
    'cvv': 'رمز التحقق CVV',
    'account_number': 'رقم الحساب',
    'account_holder': 'صاحب الحساب',
    'account_type': 'نوع الحساب',
    'bank_name': 'اسم البنك',
    'bank_code': 'رمز البنك',
    'branch_name': 'اسم الفرع',
    'branch_code': 'رمز الفرع',
    'swift_code': 'رمز SWIFT',
    'iban': 'رقم IBAN',
    'routing_number': 'رقم التوجيه',
    'wallet_id': 'معرف المحفظة',
    'wallet_address': 'عنوان المحفظة',
    'wallet_type': 'نوع المحفظة',
    'wallet_provider': 'مزود المحفظة',
    'beneficiary_name': 'اسم المستفيد',
    'beneficiary_account': 'حساب المستفيد',
    'beneficiary_bank': 'بنك المستفيد',
    'beneficiary_relationship': 'العلاقة بالمستفيد',
    'beneficiary_type': 'نوع المستفيد',
    'transaction_id': 'معرف المعاملة',
    'transaction_date': 'تاريخ المعاملة',
    'transaction_time': 'وقت المعاملة',
    'transaction_type': 'نوع المعاملة',
    'transaction_status': 'حالة المعاملة',
    'transaction_amount': 'مبلغ المعاملة',
    'transaction_fee': 'رسوم المعاملة',
    'transaction_total': 'إجمالي المعاملة',
    'transaction_description': 'وصف المعاملة',
    'transaction_reference': 'مرجع المعاملة',
    'transaction_category': 'فئة المعاملة',
    'transaction_note': 'ملاحظة المعاملة',
    'transaction_receipt': 'إيصال المعاملة',
    'transaction_invoice': 'فاتورة المعاملة',
    'transaction_sender': 'مرسل المعاملة',
    'transaction_receiver': 'مستلم المعاملة',
    'transaction_source': 'مصدر المعاملة',
    'transaction_destination': 'وجهة المعاملة',
    'transaction_currency': 'عملة المعاملة',
    'transaction_exchange_rate': 'سعر الصرف',
    'transaction_converted_amount': 'المبلغ المحول',
    'transaction_original_amount': 'المبلغ الأصلي',
    'transaction_original_currency': 'العملة الأصلية',
    'transaction_converted_currency': 'العملة المحولة',
    'bill_payment': 'دفع الفاتورة',
    'bill_details': 'تفاصيل الفاتورة',
    'bill_number': 'رقم الفاتورة',
    'bill_date': 'تاريخ الفاتورة',
    'bill_due_date': 'تاريخ استحقاق الفاتورة',
    'bill_amount': 'مبلغ الفاتورة',
    'bill_status': 'حالة الفاتورة',
    'bill_type': 'نوع الفاتورة',
    'bill_provider': 'مزود الفاتورة',
    'bill_category': 'فئة الفاتورة',
    'bill_description': 'وصف الفاتورة',
    'bill_reference': 'مرجع الفاتورة',
    'bill_payment_date': 'تاريخ دفع الفاتورة',
    'bill_payment_status': 'حالة دفع الفاتورة',
    'bill_payment_method': 'طريقة دفع الفاتورة',
    'bill_payment_reference': 'مرجع دفع الفاتورة',
    'bill_payment_amount': 'مبلغ دفع الفاتورة',
    'bill_payment_fee': 'رسوم دفع الفاتورة',
    'bill_payment_total': 'إجمالي دفع الفاتورة',
    'bill_payment_description': 'وصف دفع الفاتورة',
    'bill_payment_note': 'ملاحظة دفع الفاتورة',
    'bill_payment_receipt': 'إيصال دفع الفاتورة',
    'bill_payment_invoice': 'فاتورة دفع الفاتورة',
    'bill_payment_source': 'مصدر دفع الفاتورة',
    'bill_payment_destination': 'وجهة دفع الفاتورة',
    'bill_payment_currency': 'عملة دفع الفاتورة',
    'bill_payment_exchange_rate': 'سعر صرف دفع الفاتورة',
    'bill_payment_converted_amount': 'مبلغ دفع الفاتورة المحول',
    'bill_payment_original_amount': 'مبلغ دفع الفاتورة الأصلي',
    'bill_payment_original_currency': 'عملة دفع الفاتورة الأصلية',
    'bill_payment_converted_currency': 'عملة دفع الفاتورة المحولة',
    'mobile_top_up': 'شحن رصيد الهاتف',
    'mobile_number': 'رقم الهاتف',
    'mobile_operator': 'مشغل الهاتف',
    'mobile_plan': 'خطة الهاتف',
    'mobile_amount': 'مبلغ الشحن',
    'mobile_top_up_confirmation': 'تأكيد شحن رصيد الهاتف',
    'mobile_top_up_successful': 'تم شحن رصيد الهاتف بنجاح',
    'mobile_top_up_failed': 'فشل شحن رصيد الهاتف',
    'mobile_top_up_details': 'تفاصيل شحن رصيد الهاتف',
    'mobile_top_up_date': 'تاريخ شحن رصيد الهاتف',
    'mobile_top_up_time': 'وقت شحن رصيد الهاتف',
    'mobile_top_up_status': 'حالة شحن رصيد الهاتف',
    'mobile_top_up_amount': 'مبلغ شحن رصيد الهاتف',
    'mobile_top_up_fee': 'رسوم شحن رصيد الهاتف',
    'mobile_top_up_total': 'إجمالي شحن رصيد الهاتف',
    'mobile_top_up_description': 'وصف شحن رصيد الهاتف',
    'mobile_top_up_reference': 'مرجع شحن رصيد الهاتف',
    'mobile_top_up_note': 'ملاحظة شحن رصيد الهاتف',
    'mobile_top_up_receipt': 'إيصال شحن رصيد الهاتف',
    'mobile_top_up_source': 'مصدر شحن رصيد الهاتف',
    'mobile_top_up_destination': 'وجهة شحن رصيد الهاتف',
    'mobile_top_up_currency': 'عملة شحن رصيد الهاتف',
    'mobile_top_up_exchange_rate': 'سعر صرف شحن رصيد الهاتف',
    'mobile_top_up_converted_amount': 'مبلغ شحن رصيد الهاتف المحول',
    'mobile_top_up_original_amount': 'مبلغ شحن رصيد الهاتف الأصلي',
    'mobile_top_up_original_currency': 'عملة شحن رصيد الهاتف الأصلية',
    'mobile_top_up_converted_currency': 'عملة شحن رصيد الهاتف المحولة',
    'qr_code': 'رمز QR',
    'qr_code_scan': 'مسح رمز QR',
    'qr_code_generate': 'إنشاء رمز QR',
    'qr_code_share': 'مشاركة رمز QR',
    'qr_code_save': 'حفظ رمز QR',
    'qr_code_copy': 'نسخ رمز QR',
    'qr_code_print': 'طباعة رمز QR',
    'qr_code_download': 'تنزيل رمز QR',
    'qr_code_upload': 'رفع رمز QR',
    'qr_code_details': 'تفاصيل رمز QR',
    'qr_code_type': 'نوع رمز QR',
    'qr_code_value': 'قيمة رمز QR',
    'qr_code_format': 'تنسيق رمز QR',
    'qr_code_size': 'حجم رمز QR',
    'qr_code_color': 'لون رمز QR',
    'qr_code_background': 'خلفية رمز QR',
    'qr_code_logo': 'شعار رمز QR',
    'qr_code_error_correction': 'تصحيح أخطاء رمز QR',
    'qr_code_margin': 'هامش رمز QR',
    'qr_code_version': 'إصدار رمز QR',
    'qr_code_mask': 'قناع رمز QR',
    'qr_code_encoding': 'ترميز رمز QR',
    'qr_code_mode': 'وضع رمز QR',
    'qr_code_structure': 'بنية رمز QR',
    'qr_code_module': 'وحدة رمز QR',
    'qr_code_position': 'موضع رمز QR',
    'qr_code_alignment': 'محاذاة رمز QR',
    'qr_code_timing': 'توقيت رمز QR',
    'qr_code_format_info': 'معلومات تنسيق رمز QR',
    'qr_code_version_info': 'معلومات إصدار رمز QR',
    'qr_code_data': 'بيانات رمز QR',
    'qr_code_checksum': 'المجموع الاختباري لرمز QR',
    'qr_code_error': 'خطأ في رمز QR',
    'qr_code_warning': 'تحذير رمز QR',
    'qr_code_info': 'معلومات رمز QR',
    'qr_code_success': 'نجاح رمز QR',
    'qr_code_failure': 'فشل رمز QR',
    'qr_code_invalid': 'رمز QR غير صالح',
    'qr_code_valid': 'رمز QR صالح',
    'qr_code_expired': 'رمز QR منتهي الصلاحية',
    'qr_code_active': 'رمز QR نشط',
    'qr_code_inactive': 'رمز QR غير نشط',
    'qr_code_pending': 'رمز QR معلق',
    'qr_code_completed': 'رمز QR مكتمل',
    'qr_code_cancelled': 'رمز QR ملغى',
    'qr_code_rejected': 'رمز QR مرفوض',
    'qr_code_approved': 'رمز QR موافق عليه',
    'qr_code_processing': 'رمز QR قيد المعالجة',
    'qr_code_scheduled': 'رمز QR مجدول',
    'qr_code_recurring': 'رمز QR متكرر',
    'qr_code_one_time': 'رمز QR لمرة واحدة',
    'qr_code_dynamic': 'رمز QR ديناميكي',
    'qr_code_static': 'رمز QR ثابت',
    'qr_code_payment': 'رمز QR للدفع',
    'qr_code_transfer': 'رمز QR للتحويل',
    'qr_code_deposit': 'رمز QR للإيداع',
    'qr_code_withdrawal': 'رمز QR للسحب',
    'qr_code_bill_payment': 'رمز QR لدفع الفاتورة',
    'qr_code_mobile_top_up': 'رمز QR لشحن رصيد الهاتف',
    'qr_code_card': 'رمز QR للبطاقة',
    'qr_code_account': 'رمز QR للحساب',
    'qr_code_wallet': 'رمز QR للمحفظة',
    'qr_code_beneficiary': 'رمز QR للمستفيد',
    'qr_code_transaction': 'رمز QR للمعاملة',
    'qr_code_payment_request': 'رمز QR لطلب الدفع',
    'qr_code_payment_response': 'رمز QR للرد على طلب الدفع',
    'qr_code_payment_confirmation': 'رمز QR لتأكيد الدفع',
    'qr_code_payment_receipt': 'رمز QR لإيصال الدفع',
    'qr_code_payment_invoice': 'رمز QR لفاتورة الدفع',
    'qr_code_payment_details': 'رمز QR لتفاصيل الدفع',
    'qr_code_payment_summary': 'رمز QR لملخص الدفع',
    'qr_code_payment_history': 'رمز QR لسجل الدفع',
    'qr_code_payment_status': 'رمز QR لحالة الدفع',
    'qr_code_payment_method': 'رمز QR لطريقة الدفع',
    'qr_code_payment_source': 'رمز QR لمصدر الدفع',
    'qr_code_payment_destination': 'رمز QR لوجهة الدفع',
    'qr_code_payment_amount': 'رمز QR لمبلغ الدفع',
    'qr_code_payment_currency': 'رمز QR لعملة الدفع',
    'qr_code_payment_date': 'رمز QR لتاريخ الدفع',
    'qr_code_payment_time': 'رمز QR لوقت الدفع',
    'qr_code_payment_reference': 'رمز QR لمرجع الدفع',
    'qr_code_payment_description': 'رمز QR لوصف الدفع',
    'qr_code_payment_note': 'رمز QR لملاحظة الدفع',
    'qr_code_payment_category': 'رمز QR لفئة الدفع',
    'qr_code_payment_type': 'رمز QR لنوع الدفع',
    'qr_code_payment_fee': 'رمز QR لرسوم الدفع',
    'qr_code_payment_total': 'رمز QR لإجمالي الدفع',
    'qr_code_payment_subtotal': 'رمز QR للمجموع الفرعي للدفع',
    'qr_code_payment_tax': 'رمز QR لضريبة الدفع',
    'qr_code_payment_discount': 'رمز QR لخصم الدفع',
    'qr_code_payment_tip': 'رمز QR لإكرامية الدفع',
    'qr_code_payment_shipping': 'رمز QR لشحن الدفع',
    'qr_code_payment_handling': 'رمز QR لمناولة الدفع',
    'qr_code_payment_insurance': 'رمز QR لتأمين الدفع',
    'qr_code_payment_duty': 'رمز QR لرسوم الدفع',
    'qr_code_payment_tax_rate': 'رمز QR لمعدل ضريبة الدفع',
    'qr_code_payment_tax_amount': 'رمز QR لمبلغ ضريبة الدفع',
    'qr_code_payment_tax_included': 'رمز QR لضريبة الدفع المضمنة',
    'qr_code_payment_tax_excluded': 'رمز QR لضريبة الدفع المستبعدة',
    'qr_code_payment_discount_rate': 'رمز QR لمعدل خصم الدفع',
    'qr_code_payment_discount_amount': 'رمز QR لمبلغ خصم الدفع',
    'qr_code_payment_discount_type': 'رمز QR لنوع خصم الدفع',
    'qr_code_payment_discount_code': 'رمز QR لرمز خصم الدفع',
    'qr_code_payment_discount_description': 'رمز QR لوصف خصم الدفع',
    'qr_code_payment_discount_expiry': 'رمز QR لانتهاء صلاحية خصم الدفع',
    'qr_code_payment_discount_start': 'رمز QR لبدء خصم الدفع',
    'qr_code_payment_discount_end': 'رمز QR لنهاية خصم الدفع',
    'qr_code_payment_discount_status': 'رمز QR لحالة خصم الدفع',
    'qr_code_payment_discount_condition': 'رمز QR لشرط خصم الدفع',
    'qr_code_payment_discount_minimum': 'رمز QR للحد الأدنى لخصم الدفع',
    'qr_code_payment_discount_maximum': 'رمز QR للحد الأقصى لخصم الدفع',
    'qr_code_payment_discount_limit': 'رمز QR لحد خصم الدفع',
    'qr_code_payment_discount_usage': 'رمز QR لاستخدام خصم الدفع',
    'qr_code_payment_discount_remaining': 'رمز QR لخصم الدفع المتبقي',
    'qr_code_payment_discount_used': 'رمز QR لخصم الدفع المستخدم',
    'qr_code_payment_discount_available': 'رمز QR لخصم الدفع المتاح',
    'qr_code_payment_discount_unavailable': 'رمز QR لخصم الدفع غير المتاح',
    'qr_code_payment_discount_active': 'رمز QR لخصم الدفع النشط',
    'qr_code_payment_discount_inactive': 'رمز QR لخصم الدفع غير النشط',
    'qr_code_payment_discount_expired': 'رمز QR لخصم الدفع المنتهي',
    'qr_code_payment_discount_valid': 'رمز QR لخصم الدفع الصالح',
    'qr_code_payment_discount_invalid': 'رمز QR لخصم الدفع غير الصالح',
    'qr_code_payment_discount_applied': 'رمز QR لخصم الدفع المطبق',
    'qr_code_payment_discount_not_applied': 'رمز QR لخصم الدفع غير المطبق',
    'qr_code_payment_discount_percentage': 'رمز QR لنسبة خصم الدفع',
    'qr_code_payment_discount_fixed': 'رمز QR لخصم الدفع الثابت',
    'qr_code_payment_discount_free': 'رمز QR لخصم الدفع المجاني',
    'qr_code_payment_discount_buy_one_get_one': 'رمز QR لخصم الدفع اشتر واحدة واحصل على واحدة',
    'qr_code_payment_discount_buy_one_get_one_free': 'رمز QR لخصم الدفع اشتر واحدة واحصل على واحدة مجانًا',
    'qr_code_payment_discount_buy_one_get_one_half_price': 'رمز QR لخصم الدفع اشتر واحدة واحصل على واحدة بنصف السعر',
    'qr_code_payment_discount_buy_two_get_one_free': 'رمز QR لخصم الدفع اشتر اثنتين واحصل على واحدة مجانًا',
    'qr_code_payment_discount_buy_three_get_one_free': 'رمز QR لخصم الدفع اشتر ثلاثة واحصل على واحدة مجانًا',
    'qr_code_payment_discount_buy_four_get_one_free': 'رمز QR لخصم الدفع اشتر أربعة واحصل على واحدة مجانًا',
    'qr_code_payment_discount_buy_five_get_one_free': 'رمز QR لخصم الدفع اشتر خمسة واحصل على واحدة مجانًا',
    'qr_code_payment_discount_buy_one_get_two_free': 'رمز QR لخصم الدفع اشتر واحدة واحصل على اثنتين مجانًا',
    'qr_code_payment_discount_buy_one_get_three_free': 'رمز QR لخصم الدفع اشتر واحدة واحصل على ثلاثة مجانًا',
    'qr_code_payment_discount_buy_one_get_four_free': 'رمز QR لخصم الدفع اشتر واحدة واحصل على أربعة مجانًا',
    'qr_code_payment_discount_buy_one_get_five_free': 'رمز QR لخصم الدفع اشتر واحدة واحصل على خمسة مجانًا',
    'qr_code_payment_discount_free_shipping': 'رمز QR لخصم الدفع شحن مجاني',
    'qr_code_payment_discount_free_gift': 'رمز QR لخصم الدفع هدية مجانية',
    'qr_code_payment_discount_free_sample': 'رمز QR لخصم الدفع عينة مجانية',
    'qr_code_payment_discount_free_trial': 'رمز QR لخصم الدفع تجربة مجانية',
    'qr_code_payment_discount_free_upgrade': 'رمز QR لخصم الدفع ترقية مجانية',
    'qr_code_payment_discount_free_installation': 'رمز QR لخصم الدفع تركيب مجاني',
    'qr_code_payment_discount_free_setup': 'رمز QR لخصم الدفع إعداد مجاني',
    'qr_code_payment_discount_free_support': 'رمز QR لخصم الدفع دعم مجاني',
    'qr_code_payment_discount_free_maintenance': 'رمز QR لخصم الدفع صيانة مجانية',
    'qr_code_payment_discount_free_warranty': 'رمز QR لخصم الدفع ضمان مجاني',
    'qr_code_payment_discount_free_insurance': 'رمز QR لخصم الدفع تأمين مجاني',
    'qr_code_payment_discount_free_delivery': 'رمز QR لخصم الدفع توصيل مجاني',
    'qr_code_payment_discount_free_return': 'رمز QR لخصم الدفع إرجاع مجاني',
    'qr_code_payment_discount_free_exchange': 'رمز QR لخصم الدفع استبدال مجاني',
    'qr_code_payment_discount_free_refund': 'رمز QR لخصم الدفع استرداد مجاني',
    'qr_code_payment_discount_free_cancellation': 'رمز QR لخصم الدفع إلغاء مجاني',
    'qr_code_payment_discount_free_modification': 'رمز QR لخصم الدفع تعديل مجاني',
    'qr_code_payment_discount_free_customization': 'رمز QR لخصم الدفع تخصيص مجاني',
    'qr_code_payment_discount_free_personalization': 'رمز QR لخصم الدفع تشخيص مجاني',
    'qr_code_payment_discount_free_engraving': 'رمز QR لخصم الدفع نقش مجاني',
    'qr_code_payment_discount_free_printing': 'رمز QR لخصم الدفع طباعة مجانية',
    'qr_code_payment_discount_free_packaging': 'رمز QR لخصم الدفع تغليف مجاني',
    'qr_code_payment_discount_free_gift_wrapping': 'رمز QR لخصم الدفع تغليف هدايا مجاني',
    'qr_code_payment_discount_free_gift_card': 'رمز QR لخصم الدفع بطاقة هدية مجانية',
    'qr_code_payment_discount_free_gift_message': 'رمز QR لخصم الدفع رسالة هدية مجانية',
    'qr_code_payment_discount_free_gift_receipt': 'رمز QR لخصم الدفع إيصال هدية مجاني',
    'qr_code_payment_discount_free_gift_box': 'رمز QR لخصم الدفع صندوق هدية مجاني',
    'qr_code_payment_discount_free_gift_bag': 'رمز QR لخصم الدفع كيس هدية مجاني',
    'qr_code_payment_discount_free_gift_ribbon': 'رمز QR لخصم الدفع شريط هدية مجاني',
    'qr_code_payment_discount_free_gift_bow': 'رمز QR لخصم الدفع فيونكة هدية مجانية',
    'qr_code_payment_discount_free_gift_tag': 'رمز QR لخصم الدفع بطاقة هدية مجانية',
    'qr_code_payment_discount_free_gift_tissue': 'رمز QR لخصم الدفع ورق هدية مجاني',
    'qr_code_payment_discount_free_gift_sticker': 'رمز QR لخصم الدفع ملصق هدية مجاني',
    'qr_code_payment_discount_free_gift_label': 'رمز QR لخصم الدفع ملصق هدية مجاني',
    'qr_code_payment_discount_free_gift_seal': 'رمز QR لخصم الدفع ختم هدية مجاني',
    'qr_code_payment_discount_free_gift_stamp': 'رمز QR لخصم الدفع طابع هدية مجاني',
    'qr_code_payment_discount_free_gift_envelope': 'رمز QR لخصم الدفع ظرف هدية مجاني',
    'qr_code_payment_discount_free_gift_card_envelope': 'رمز QR لخصم الدفع ظرف بطاقة هدية مجاني',
    'qr_code_payment_discount_free_gift_card_holder': 'رمز QR لخصم الدفع حامل بطاقة هدية مجاني',
    'qr_code_payment_discount_free_gift_card_sleeve': 'رمز QR لخصم الدفع غلاف بطاقة هدية مجاني',
    'qr_code_payment_discount_free_gift_card_box': 'رمز QR لخصم الدفع صندوق بطاقة هدية مجاني',
    'qr_code_payment_discount_free_gift_card_bag': 'رمز QR لخصم الدفع كيس بطاقة هدية مجاني',
    'qr_code_payment_discount_free_gift_card_ribbon': 'رمز QR لخصم الدفع شريط بطاقة هدية مجاني',
    'qr_code_payment_discount_free_gift_card_bow': 'رمز QR لخصم الدفع فيونكة بطاقة هدية مجانية',
    'qr_code_payment_discount_free_gift_card_tag': 'رمز QR لخصم الدفع بطاقة بطاقة هدية مجانية',
    'qr_code_payment_discount_free_gift_card_tissue': 'رمز QR لخصم الدفع ورق بطاقة هدية مجاني',
    'qr_code_payment_discount_free_gift_card_sticker': 'رمز QR لخصم الدفع ملصق بطاقة هدية مجاني',
    'qr_code_payment_discount_free_gift_card_label': 'رمز QR لخصم الدفع ملصق بطاقة هدية مجاني',
    'qr_code_payment_discount_free_gift_card_seal': 'رمز QR لخصم الدفع ختم بطاقة هدية مجاني',
    'qr_code_payment_discount_free_gift_card_stamp': 'رمز QR لخصم الدفع طابع بطاقة هدية مجاني',
    'qr_code_payment_discount_free_gift_card_envelope': 'رمز QR لخصم الدفع ظرف بطاقة هدية مجاني',
  };
  
  /// Map of localized values for English
  static const Map<String, String> _localizedValuesEn = {
    // General
    'app_name': 'MPay Plus',
    'ok': 'OK',
    'cancel': 'Cancel',
    'save': 'Save',
    'delete': 'Delete',
    'edit': 'Edit',
    'close': 'Close',
    'back': 'Back',
    'next': 'Next',
    'previous': 'Previous',
    'done': 'Done',
    'loading': 'Loading...',
    'error': 'Error',
    'success': 'Success',
    'warning': 'Warning',
    'info': 'Info',
    'retry': 'Retry',
    'no_data': 'No data',
    'search': 'Search',
    'filter': 'Filter',
    'sort': 'Sort',
    'settings': 'Settings',
    'profile': 'Profile',
    'logout': 'Logout',
    'login': 'Login',
    'register': 'Register',
    'forgot_password': 'Forgot Password?',
    'reset_password': 'Reset Password',
    'change_password': 'Change Password',
    'confirm_password': 'Confirm Password',
    'password': 'Password',
    'email': 'Email',
    'phone': 'Phone',
    'username': 'Username',
    'name': 'Name',
    'first_name': 'First Name',
    'last_name': 'Last Name',
    'address': 'Address',
    'city': 'City',
    'country': 'Country',
    'postal_code': 'Postal Code',
    'date': 'Date',
    'time': 'Time',
    'amount': 'Amount',
    'currency': 'Currency',
    'description': 'Description',
    'category': 'Category',
    'status': 'Status',
    'type': 'Type',
    'id': 'ID',
    'reference': 'Reference',
    'details': 'Details',
    'summary': 'Summary',
    'total': 'Total',
    'subtotal': 'Subtotal',
    'tax': 'Tax',
    'discount': 'Discount',
    'fee': 'Fee',
    'balance': 'Balance',
    'available_balance': 'Available Balance',
    'pending_balance': 'Pending Balance',
    'transaction': 'Transaction',
    'transactions': 'Transactions',
    'payment': 'Payment',
    'payments': 'Payments',
    'transfer': 'Transfer',
    'transfers': 'Transfers',
    'deposit': 'Deposit',
    'deposits': 'Deposits',
    'withdrawal': 'Withdrawal',
    'withdrawals': 'Withdrawals',
    'card': 'Card',
    'cards': 'Cards',
    'account': 'Account',
    'accounts': 'Accounts',
    'wallet': 'Wallet',
    'wallets': 'Wallets',
    'beneficiary': 'Beneficiary',
    'beneficiaries': 'Beneficiaries',
    'notification': 'Notification',
    'notifications': 'Notifications',
    'message': 'Message',
    'messages': 'Messages',
    'support': 'Support',
    'help': 'Help',
    'faq': 'FAQ',
    'terms': 'Terms & Conditions',
    'privacy': 'Privacy Policy',
    'about': 'About',
    'contact': 'Contact Us',
    'version': 'Version',
    'language': 'Language',
    'theme': 'Theme',
    'dark_mode': 'Dark Mode',
    'light_mode': 'Light Mode',
    'system_mode': 'System Mode',
    'accessibility': 'Accessibility',
    'security': 'Security',
    'biometrics': 'Biometrics',
    'face_id': 'Face ID',
    'touch_id': 'Touch ID',
    'fingerprint': 'Fingerprint',
    'pin': 'PIN',
    'otp': 'OTP',
    'verification_code': 'Verification Code',
    'verification': 'Verification',
    'confirm': 'Confirm',
    'continue': 'Continue',
    'skip': 'Skip',
    'yes': 'Yes',
    'no': 'No',
    'enable': 'Enable',
    'disable': 'Disable',
    'enabled': 'Enabled',
    'disabled': 'Disabled',
    'active': 'Active',
    'inactive': 'Inactive',
    'pending': 'Pending',
    'completed': 'Completed',
    'failed': 'Failed',
    'cancelled': 'Cancelled',
    'rejected': 'Rejected',
    'approved': 'Approved',
    'processing': 'Processing',
    'scheduled': 'Scheduled',
    'recurring': 'Recurring',
    'one_time': 'One Time',
    'daily': 'Daily',
    'weekly': 'Weekly',
    'monthly': 'Monthly',
    'yearly': 'Yearly',
    'today': 'Today',
    'yesterday': 'Yesterday',
    'tomorrow': 'Tomorrow',
    'this_week': 'This Week',
    'last_week': 'Last Week',
    'this_month': 'This Month',
    'last_month': 'Last Month',
    'this_year': 'This Year',
    'last_year': 'Last Year',
    'custom_range': 'Custom Range',
    'start_date': 'Start Date',
    'end_date': 'End Date',
    'from': 'From',
    'to': 'To',
    'min': 'Min',
    'max': 'Max',
    'all': 'All',
    'none': 'None',
    'select_all': 'Select All',
    'select_none': 'Select None',
    'select': 'Select',
    'selected': 'Selected',
    'choose': 'Choose',
    'choose_file': 'Choose File',
    'choose_image': 'Choose Image',
    'upload': 'Upload',
    'download': 'Download',
    'share': 'Share',
    'copy': 'Copy',
    'paste': 'Paste',
    'cut': 'Cut',
    'undo': 'Undo',
    'redo': 'Redo',
    'add': 'Add',
    'remove': 'Remove',
    'create': 'Create',
    'update': 'Update',
    'refresh': 'Refresh',
    'reload': 'Reload',
    'reset': 'Reset',
    'clear': 'Clear',
    'clear_all': 'Clear All',
    'apply': 'Apply',
    'submit': 'Submit',
    'send': 'Send',
    'receive': 'Receive',
    'request': 'Request',
    'accept': 'Accept',
    'decline': 'Decline',
    'block': 'Block',
    'unblock': 'Unblock',
    'report': 'Report',
    'favorite': 'Favorite',
    'unfavorite': 'Unfavorite',
    'bookmark': 'Bookmark',
    'unbookmark': 'Unbookmark',
    'like': 'Like',
    'unlike': 'Unlike',
    'follow': 'Follow',
    'unfollow': 'Unfollow',
    'more': 'More',
    'less': 'Less',
    'show_more': 'Show More',
    'show_less': 'Show Less',
    'expand': 'Expand',
    'collapse': 'Collapse',
    'open': 'Open',
    'close': 'Close',
    'start': 'Start',
    'stop': 'Stop',
    'pause': 'Pause',
    'resume': 'Resume',
    'play': 'Play',
    'replay': 'Replay',
    'forward': 'Forward',
    'backward': 'Backward',
    'first': 'First',
    'last': 'Last',
    'top': 'Top',
    'bottom': 'Bottom',
    'up': 'Up',
    'down': 'Down',
    'left': 'Left',
    'right': 'Right',
    'center': 'Center',
    'horizontal': 'Horizontal',
    'vertical': 'Vertical',
    'portrait': 'Portrait',
    'landscape': 'Landscape',
    'rotate': 'Rotate',
    'flip': 'Flip',
    'zoom_in': 'Zoom In',
    'zoom_out': 'Zoom Out',
    'fit': 'Fit',
    'fill': 'Fill',
    'crop': 'Crop',
    'resize': 'Resize',
    'scale': 'Scale',
    'aspect_ratio': 'Aspect Ratio',
    'width': 'Width',
    'height': 'Height',
    'size': 'Size',
    'small': 'Small',
    'medium': 'Medium',
    'large': 'Large',
    'extra_small': 'Extra Small',
    'extra_large': 'Extra Large',
    'custom': 'Custom',
    'default': 'Default',
    'auto': 'Auto',
    'manual': 'Manual',
    'on': 'On',
    'off': 'Off',
    'high': 'High',
    'medium': 'Medium',
    'low': 'Low',
    'normal': 'Normal',
    'fast': 'Fast',
    'slow': 'Slow',
    'new': 'New',
    'old': 'Old',
    'recent': 'Recent',
    'popular': 'Popular',
    'trending': 'Trending',
    'featured': 'Featured',
    'recommended': 'Recommended',
    'related': 'Related',
    'similar': 'Similar',
    'other': 'Other',
    'alternative': 'Alternative',
    'main': 'Main',
    'secondary': 'Secondary',
    'tertiary': 'Tertiary',
    'primary': 'Primary',
    'accent': 'Accent',
    'background': 'Background',
    'foreground': 'Foreground',
    'transparent': 'Transparent',
    'opaque': 'Opaque',
    'solid': 'Solid',
    'gradient': 'Gradient',
    'pattern': 'Pattern',
    'texture': 'Texture',
    'shadow': 'Shadow',
    'blur': 'Blur',
    'sharp': 'Sharp',
    'rounded': 'Rounded',
    'square': 'Square',
    'circle': 'Circle',
    'oval': 'Oval',
    'rectangle': 'Rectangle',
    'triangle': 'Triangle',
    'polygon': 'Polygon',
    'star': 'Star',
    'heart': 'Heart',
    'arrow': 'Arrow',
    'line': 'Line',
    'curve': 'Curve',
    'path': 'Path',
    'shape': 'Shape',
    'icon': 'Icon',
    'image': 'Image',
    'video': 'Video',
    'audio': 'Audio',
    'file': 'File',
    'folder': 'Folder',
    'document': 'Document',
    'text': 'Text',
    'number': 'Number',
    'boolean': 'Boolean',
    'date': 'Date',
    'time': 'Time',
    'datetime': 'Date & Time',
    'duration': 'Duration',
    'interval': 'Interval',
    'period': 'Period',
    'frequency': 'Frequency',
    'rate': 'Rate',
    'speed': 'Speed',
    'velocity': 'Velocity',
    'acceleration': 'Acceleration',
    'force': 'Force',
    'pressure': 'Pressure',
    'temperature': 'Temperature',
    'volume': 'Volume',
    'area': 'Area',
    'length': 'Length',
    'distance': 'Distance',
    'weight': 'Weight',
    'mass': 'Mass',
    'density': 'Density',
    'energy': 'Energy',
    'power': 'Power',
    'voltage': 'Voltage',
    'current': 'Current',
    'resistance': 'Resistance',
    'capacity': 'Capacity',
    'charge': 'Charge',
    'frequency': 'Frequency',
    'wavelength': 'Wavelength',
    'amplitude': 'Amplitude',
    'intensity': 'Intensity',
    'luminosity': 'Luminosity',
    'brightness': 'Brightness',
    'contrast': 'Contrast',
    'saturation': 'Saturation',
    'hue': 'Hue',
    'opacity': 'Opacity',
    'transparency': 'Transparency',
    'alpha': 'Alpha',
    'beta': 'Beta',
    'gamma': 'Gamma',
    'delta': 'Delta',
    'epsilon': 'Epsilon',
    'zeta': 'Zeta',
    'eta': 'Eta',
    'theta': 'Theta',
    'iota': 'Iota',
    'kappa': 'Kappa',
    'lambda': 'Lambda',
    'mu': 'Mu',
    'nu': 'Nu',
    'xi': 'Xi',
    'omicron': 'Omicron',
    'pi': 'Pi',
    'rho': 'Rho',
    'sigma': 'Sigma',
    'tau': 'Tau',
    'upsilon': 'Upsilon',
    'phi': 'Phi',
    'chi': 'Chi',
    'psi': 'Psi',
    'omega': 'Omega',
    
    // App specific
    'home': 'Home',
    'dashboard': 'Dashboard',
    'send_money': 'Send Money',
    'request_money': 'Request Money',
    'scan_qr': 'Scan QR',
    'pay_bills': 'Pay Bills',
    'top_up': 'Top Up',
    'cash_out': 'Cash Out',
    'my_cards': 'My Cards',
    'my_accounts': 'My Accounts',
    'my_wallets': 'My Wallets',
    'my_beneficiaries': 'My Beneficiaries',
    'transaction_history': 'Transaction History',
    'recent_transactions': 'Recent Transactions',
    'transaction_details': 'Transaction Details',
    'payment_confirmation': 'Payment Confirmation',
    'payment_successful': 'Payment Successful',
    'payment_failed': 'Payment Failed',
    'transfer_confirmation': 'Transfer Confirmation',
    'transfer_successful': 'Transfer Successful',
    'transfer_failed': 'Transfer Failed',
    'add_money': 'Add Money',
    'withdraw_money': 'Withdraw Money',
    'add_card': 'Add Card',
    'add_account': 'Add Account',
    'add_wallet': 'Add Wallet',
    'add_beneficiary': 'Add Beneficiary',
    'edit_card': 'Edit Card',
    'edit_account': 'Edit Account',
    'edit_wallet': 'Edit Wallet',
    'edit_beneficiary': 'Edit Beneficiary',
    'delete_card': 'Delete Card',
    'delete_account': 'Delete Account',
    'delete_wallet': 'Delete Wallet',
    'delete_beneficiary': 'Delete Beneficiary',
    'card_details': 'Card Details',
    'account_details': 'Account Details',
    'wallet_details': 'Wallet Details',
    'beneficiary_details': 'Beneficiary Details',
    'card_number': 'Card Number',
    'card_holder': 'Card Holder',
    'expiry_date': 'Expiry Date',
    'cvv': 'CVV',
    'account_number': 'Account Number',
    'account_holder': 'Account Holder',
    'account_type': 'Account Type',
    'bank_name': 'Bank Name',
    'bank_code': 'Bank Code',
    'branch_name': 'Branch Name',
    'branch_code': 'Branch Code',
    'swift_code': 'SWIFT Code',
    'iban': 'IBAN',
    'routing_number': 'Routing Number',
    'wallet_id': 'Wallet ID',
    'wallet_address': 'Wallet Address',
    'wallet_type': 'Wallet Type',
    'wallet_provider': 'Wallet Provider',
    'beneficiary_name': 'Beneficiary Name',
    'beneficiary_account': 'Beneficiary Account',
    'beneficiary_bank': 'Beneficiary Bank',
    'beneficiary_relationship': 'Beneficiary Relationship',
    'beneficiary_type': 'Beneficiary Type',
    'transaction_id': 'Transaction ID',
    'transaction_date': 'Transaction Date',
    'transaction_time': 'Transaction Time',
    'transaction_type': 'Transaction Type',
    'transaction_status': 'Transaction Status',
    'transaction_amount': 'Transaction Amount',
    'transaction_fee': 'Transaction Fee',
    'transaction_total': 'Transaction Total',
    'transaction_description': 'Transaction Description',
    'transaction_reference': 'Transaction Reference',
    'transaction_category': 'Transaction Category',
    'transaction_note': 'Transaction Note',
    'transaction_receipt': 'Transaction Receipt',
    'transaction_invoice': 'Transaction Invoice',
    'transaction_sender': 'Transaction Sender',
    'transaction_receiver': 'Transaction Receiver',
    'transaction_source': 'Transaction Source',
    'transaction_destination': 'Transaction Destination',
    'transaction_currency': 'Transaction Currency',
    'transaction_exchange_rate': 'Exchange Rate',
    'transaction_converted_amount': 'Converted Amount',
    'transaction_original_amount': 'Original Amount',
    'transaction_original_currency': 'Original Currency',
    'transaction_converted_currency': 'Converted Currency',
    'bill_payment': 'Bill Payment',
    'bill_details': 'Bill Details',
    'bill_number': 'Bill Number',
    'bill_date': 'Bill Date',
    'bill_due_date': 'Bill Due Date',
    'bill_amount': 'Bill Amount',
    'bill_status': 'Bill Status',
    'bill_type': 'Bill Type',
    'bill_provider': 'Bill Provider',
    'bill_category': 'Bill Category',
    'bill_description': 'Bill Description',
    'bill_reference': 'Bill Reference',
    'bill_payment_date': 'Bill Payment Date',
    'bill_payment_status': 'Bill Payment Status',
    'bill_payment_method': 'Bill Payment Method',
    'bill_payment_reference': 'Bill Payment Reference',
    'bill_payment_amount': 'Bill Payment Amount',
    'bill_payment_fee': 'Bill Payment Fee',
    'bill_payment_total': 'Bill Payment Total',
    'bill_payment_description': 'Bill Payment Description',
    'bill_payment_note': 'Bill Payment Note',
    'bill_payment_receipt': 'Bill Payment Receipt',
    'bill_payment_invoice': 'Bill Payment Invoice',
    'bill_payment_source': 'Bill Payment Source',
    'bill_payment_destination': 'Bill Payment Destination',
    'bill_payment_currency': 'Bill Payment Currency',
    'bill_payment_exchange_rate': 'Bill Payment Exchange Rate',
    'bill_payment_converted_amount': 'Bill Payment Converted Amount',
    'bill_payment_original_amount': 'Bill Payment Original Amount',
    'bill_payment_original_currency': 'Bill Payment Original Currency',
    'bill_payment_converted_currency': 'Bill Payment Converted Currency',
    'mobile_top_up': 'Mobile Top Up',
    'mobile_number': 'Mobile Number',
    'mobile_operator': 'Mobile Operator',
    'mobile_plan': 'Mobile Plan',
    'mobile_amount': 'Mobile Amount',
    'mobile_top_up_confirmation': 'Mobile Top Up Confirmation',
    'mobile_top_up_successful': 'Mobile Top Up Successful',
    'mobile_top_up_failed': 'Mobile Top Up Failed',
    'mobile_top_up_details': 'Mobile Top Up Details',
    'mobile_top_up_date': 'Mobile Top Up Date',
    'mobile_top_up_time': 'Mobile Top Up Time',
    'mobile_top_up_status': 'Mobile Top Up Status',
    'mobile_top_up_amount': 'Mobile Top Up Amount',
    'mobile_top_up_fee': 'Mobile Top Up Fee',
    'mobile_top_up_total': 'Mobile Top Up Total',
    'mobile_top_up_description': 'Mobile Top Up Description',
    'mobile_top_up_reference': 'Mobile Top Up Reference',
    'mobile_top_up_note': 'Mobile Top Up Note',
    'mobile_top_up_receipt': 'Mobile Top Up Receipt',
    'mobile_top_up_source': 'Mobile Top Up Source',
    'mobile_top_up_destination': 'Mobile Top Up Destination',
    'mobile_top_up_currency': 'Mobile Top Up Currency',
    'mobile_top_up_exchange_rate': 'Mobile Top Up Exchange Rate',
    'mobile_top_up_converted_amount': 'Mobile Top Up Converted Amount',
    'mobile_top_up_original_amount': 'Mobile Top Up Original Amount',
    'mobile_top_up_original_currency': 'Mobile Top Up Original Currency',
    'mobile_top_up_converted_currency': 'Mobile Top Up Converted Currency',
    'qr_code': 'QR Code',
    'qr_code_scan': 'Scan QR Code',
    'qr_code_generate': 'Generate QR Code',
    'qr_code_share': 'Share QR Code',
    'qr_code_save': 'Save QR Code',
    'qr_code_copy': 'Copy QR Code',
    'qr_code_print': 'Print QR Code',
    'qr_code_download': 'Download QR Code',
    'qr_code_upload': 'Upload QR Code',
    'qr_code_details': 'QR Code Details',
    'qr_code_type': 'QR Code Type',
    'qr_code_value': 'QR Code Value',
    'qr_code_format': 'QR Code Format',
    'qr_code_size': 'QR Code Size',
    'qr_code_color': 'QR Code Color',
    'qr_code_background': 'QR Code Background',
    'qr_code_logo': 'QR Code Logo',
    'qr_code_error_correction': 'QR Code Error Correction',
    'qr_code_margin': 'QR Code Margin',
    'qr_code_version': 'QR Code Version',
    'qr_code_mask': 'QR Code Mask',
    'qr_code_encoding': 'QR Code Encoding',
    'qr_code_mode': 'QR Code Mode',
    'qr_code_structure': 'QR Code Structure',
    'qr_code_module': 'QR Code Module',
    'qr_code_position': 'QR Code Position',
    'qr_code_alignment': 'QR Code Alignment',
    'qr_code_timing': 'QR Code Timing',
    'qr_code_format_info': 'QR Code Format Info',
    'qr_code_version_info': 'QR Code Version Info',
    'qr_code_data': 'QR Code Data',
    'qr_code_checksum': 'QR Code Checksum',
    'qr_code_error': 'QR Code Error',
    'qr_code_warning': 'QR Code Warning',
    'qr_code_info': 'QR Code Info',
    'qr_code_success': 'QR Code Success',
    'qr_code_failure': 'QR Code Failure',
    'qr_code_invalid': 'QR Code Invalid',
    'qr_code_valid': 'QR Code Valid',
    'qr_code_expired': 'QR Code Expired',
    'qr_code_active': 'QR Code Active',
    'qr_code_inactive': 'QR Code Inactive',
    'qr_code_pending': 'QR Code Pending',
    'qr_code_completed': 'QR Code Completed',
    'qr_code_cancelled': 'QR Code Cancelled',
    'qr_code_rejected': 'QR Code Rejected',
    'qr_code_approved': 'QR Code Approved',
    'qr_code_processing': 'QR Code Processing',
    'qr_code_scheduled': 'QR Code Scheduled',
    'qr_code_recurring': 'QR Code Recurring',
    'qr_code_one_time': 'QR Code One Time',
    'qr_code_dynamic': 'QR Code Dynamic',
    'qr_code_static': 'QR Code Static',
    'qr_code_payment': 'QR Code Payment',
    'qr_code_transfer': 'QR Code Transfer',
    'qr_code_deposit': 'QR Code Deposit',
    'qr_code_withdrawal': 'QR Code Withdrawal',
    'qr_code_bill_payment': 'QR Code Bill Payment',
    'qr_code_mobile_top_up': 'QR Code Mobile Top Up',
    'qr_code_card': 'QR Code Card',
    'qr_code_account': 'QR Code Account',
    'qr_code_wallet': 'QR Code Wallet',
    'qr_code_beneficiary': 'QR Code Beneficiary',
    'qr_code_transaction': 'QR Code Transaction',
    'qr_code_payment_request': 'QR Code Payment Request',
    'qr_code_payment_response': 'QR Code Payment Response',
    'qr_code_payment_confirmation': 'QR Code Payment Confirmation',
    'qr_code_payment_receipt': 'QR Code Payment Receipt',
    'qr_code_payment_invoice': 'QR Code Payment Invoice',
    'qr_code_payment_details': 'QR Code Payment Details',
    'qr_code_payment_summary': 'QR Code Payment Summary',
    'qr_code_payment_history': 'QR Code Payment History',
    'qr_code_payment_status': 'QR Code Payment Status',
    'qr_code_payment_method': 'QR Code Payment Method',
    'qr_code_payment_source': 'QR Code Payment Source',
    'qr_code_payment_destination': 'QR Code Payment Destination',
    'qr_code_payment_amount': 'QR Code Payment Amount',
    'qr_code_payment_currency': 'QR Code Payment Currency',
    'qr_code_payment_date': 'QR Code Payment Date',
    'qr_code_payment_time': 'QR Code Payment Time',
    'qr_code_payment_reference': 'QR Code Payment Reference',
    'qr_code_payment_description': 'QR Code Payment Description',
    'qr_code_payment_note': 'QR Code Payment Note',
    'qr_code_payment_category': 'QR Code Payment Category',
    'qr_code_payment_type': 'QR Code Payment Type',
    'qr_code_payment_fee': 'QR Code Payment Fee',
    'qr_code_payment_total': 'QR Code Payment Total',
    'qr_code_payment_subtotal': 'QR Code Payment Subtotal',
    'qr_code_payment_tax': 'QR Code Payment Tax',
    'qr_code_payment_discount': 'QR Code Payment Discount',
    'qr_code_payment_tip': 'QR Code Payment Tip',
    'qr_code_payment_shipping': 'QR Code Payment Shipping',
    'qr_code_payment_handling': 'QR Code Payment Handling',
    'qr_code_payment_insurance': 'QR Code Payment Insurance',
    'qr_code_payment_duty': 'QR Code Payment Duty',
    'qr_code_payment_tax_rate': 'QR Code Payment Tax Rate',
    'qr_code_payment_tax_amount': 'QR Code Payment Tax Amount',
    'qr_code_payment_tax_included': 'QR Code Payment Tax Included',
    'qr_code_payment_tax_excluded': 'QR Code Payment Tax Excluded',
    'qr_code_payment_discount_rate': 'QR Code Payment Discount Rate',
    'qr_code_payment_discount_amount': 'QR Code Payment Discount Amount',
    'qr_code_payment_discount_type': 'QR Code Payment Discount Type',
    'qr_code_payment_discount_code': 'QR Code Payment Discount Code',
    'qr_code_payment_discount_description': 'QR Code Payment Discount Description',
    'qr_code_payment_discount_expiry': 'QR Code Payment Discount Expiry',
    'qr_code_payment_discount_start': 'QR Code Payment Discount Start',
    'qr_code_payment_discount_end': 'QR Code Payment Discount End',
    'qr_code_payment_discount_status': 'QR Code Payment Discount Status',
    'qr_code_payment_discount_condition': 'QR Code Payment Discount Condition',
    'qr_code_payment_discount_minimum': 'QR Code Payment Discount Minimum',
    'qr_code_payment_discount_maximum': 'QR Code Payment Discount Maximum',
    'qr_code_payment_discount_limit': 'QR Code Payment Discount Limit',
    'qr_code_payment_discount_usage': 'QR Code Payment Discount Usage',
    'qr_code_payment_discount_remaining': 'QR Code Payment Discount Remaining',
    'qr_code_payment_discount_used': 'QR Code Payment Discount Used',
    'qr_code_payment_discount_available': 'QR Code Payment Discount Available',
    'qr_code_payment_discount_unavailable': 'QR Code Payment Discount Unavailable',
    'qr_code_payment_discount_active': 'QR Code Payment Discount Active',
    'qr_code_payment_discount_inactive': 'QR Code Payment Discount Inactive',
    'qr_code_payment_discount_expired': 'QR Code Payment Discount Expired',
    'qr_code_payment_discount_valid': 'QR Code Payment Discount Valid',
    'qr_code_payment_discount_invalid': 'QR Code Payment Discount Invalid',
    'qr_code_payment_discount_applied': 'QR Code Payment Discount Applied',
    'qr_code_payment_discount_not_applied': 'QR Code Payment Discount Not Applied',
    'qr_code_payment_discount_percentage': 'QR Code Payment Discount Percentage',
    'qr_code_payment_discount_fixed': 'QR Code Payment Discount Fixed',
    'qr_code_payment_discount_free': 'QR Code Payment Discount Free',
    'qr_code_payment_discount_buy_one_get_one': 'QR Code Payment Discount Buy One Get One',
    'qr_code_payment_discount_buy_one_get_one_free': 'QR Code Payment Discount Buy One Get One Free',
    'qr_code_payment_discount_buy_one_get_one_half_price': 'QR Code Payment Discount Buy One Get One Half Price',
    'qr_code_payment_discount_buy_two_get_one_free': 'QR Code Payment Discount Buy Two Get One Free',
    'qr_code_payment_discount_buy_three_get_one_free': 'QR Code Payment Discount Buy Three Get One Free',
    'qr_code_payment_discount_buy_four_get_one_free': 'QR Code Payment Discount Buy Four Get One Free',
    'qr_code_payment_discount_buy_five_get_one_free': 'QR Code Payment Discount Buy Five Get One Free',
    'qr_code_payment_discount_buy_one_get_two_free': 'QR Code Payment Discount Buy One Get Two Free',
    'qr_code_payment_discount_buy_one_get_three_free': 'QR Code Payment Discount Buy One Get Three Free',
    'qr_code_payment_discount_buy_one_get_four_free': 'QR Code Payment Discount Buy One Get Four Free',
    'qr_code_payment_discount_buy_one_get_five_free': 'QR Code Payment Discount Buy One Get Five Free',
    'qr_code_payment_discount_free_shipping': 'QR Code Payment Discount Free Shipping',
    'qr_code_payment_discount_free_gift': 'QR Code Payment Discount Free Gift',
    'qr_code_payment_discount_free_sample': 'QR Code Payment Discount Free Sample',
    'qr_code_payment_discount_free_trial': 'QR Code Payment Discount Free Trial',
    'qr_code_payment_discount_free_upgrade': 'QR Code Payment Discount Free Upgrade',
    'qr_code_payment_discount_free_installation': 'QR Code Payment Discount Free Installation',
    'qr_code_payment_discount_free_setup': 'QR Code Payment Discount Free Setup',
    'qr_code_payment_discount_free_support': 'QR Code Payment Discount Free Support',
    'qr_code_payment_discount_free_maintenance': 'QR Code Payment Discount Free Maintenance',
    'qr_code_payment_discount_free_warranty': 'QR Code Payment Discount Free Warranty',
    'qr_code_payment_discount_free_insurance': 'QR Code Payment Discount Free Insurance',
    'qr_code_payment_discount_free_delivery': 'QR Code Payment Discount Free Delivery',
    'qr_code_payment_discount_free_return': 'QR Code Payment Discount Free Return',
    'qr_code_payment_discount_free_exchange': 'QR Code Payment Discount Free Exchange',
    'qr_code_payment_discount_free_refund': 'QR Code Payment Discount Free Refund',
    'qr_code_payment_discount_free_cancellation': 'QR Code Payment Discount Free Cancellation',
    'qr_code_payment_discount_free_modification': 'QR Code Payment Discount Free Modification',
    'qr_code_payment_discount_free_customization': 'QR Code Payment Discount Free Customization',
    'qr_code_payment_discount_free_personalization': 'QR Code Payment Discount Free Personalization',
    'qr_code_payment_discount_free_engraving': 'QR Code Payment Discount Free Engraving',
    'qr_code_payment_discount_free_printing': 'QR Code Payment Discount Free Printing',
    'qr_code_payment_discount_free_packaging': 'QR Code Payment Discount Free Packaging',
    'qr_code_payment_discount_free_gift_wrapping': 'QR Code Payment Discount Free Gift Wrapping',
    'qr_code_payment_discount_free_gift_card': 'QR Code Payment Discount Free Gift Card',
    'qr_code_payment_discount_free_gift_message': 'QR Code Payment Discount Free Gift Message',
    'qr_code_payment_discount_free_gift_receipt': 'QR Code Payment Discount Free Gift Receipt',
    'qr_code_payment_discount_free_gift_box': 'QR Code Payment Discount Free Gift Box',
    'qr_code_payment_discount_free_gift_bag': 'QR Code Payment Discount Free Gift Bag',
    'qr_code_payment_discount_free_gift_ribbon': 'QR Code Payment Discount Free Gift Ribbon',
    'qr_code_payment_discount_free_gift_bow': 'QR Code Payment Discount Free Gift Bow',
    'qr_code_payment_discount_free_gift_tag': 'QR Code Payment Discount Free Gift Tag',
    'qr_code_payment_discount_free_gift_tissue': 'QR Code Payment Discount Free Gift Tissue',
    'qr_code_payment_discount_free_gift_sticker': 'QR Code Payment Discount Free Gift Sticker',
    'qr_code_payment_discount_free_gift_label': 'QR Code Payment Discount Free Gift Label',
    'qr_code_payment_discount_free_gift_seal': 'QR Code Payment Discount Free Gift Seal',
    'qr_code_payment_discount_free_gift_stamp': 'QR Code Payment Discount Free Gift Stamp',
    'qr_code_payment_discount_free_gift_envelope': 'QR Code Payment Discount Free Gift Envelope',
    'qr_code_payment_discount_free_gift_card_envelope': 'QR Code Payment Discount Free Gift Card Envelope',
    'qr_code_payment_discount_free_gift_card_holder': 'QR Code Payment Discount Free Gift Card Holder',
    'qr_code_payment_discount_free_gift_card_sleeve': 'QR Code Payment Discount Free Gift Card Sleeve',
    'qr_code_payment_discount_free_gift_card_box': 'QR Code Payment Discount Free Gift Card Box',
    'qr_code_payment_discount_free_gift_card_bag': 'QR Code Payment Discount Free Gift Card Bag',
    'qr_code_payment_discount_free_gift_card_ribbon': 'QR Code Payment Discount Free Gift Card Ribbon',
    'qr_code_payment_discount_free_gift_card_bow': 'QR Code Payment Discount Free Gift Card Bow',
    'qr_code_payment_discount_free_gift_card_tag': 'QR Code Payment Discount Free Gift Card Tag',
    'qr_code_payment_discount_free_gift_card_tissue': 'QR Code Payment Discount Free Gift Card Tissue',
    'qr_code_payment_discount_free_gift_card_sticker': 'QR Code Payment Discount Free Gift Card Sticker',
    'qr_code_payment_discount_free_gift_card_label': 'QR Code Payment Discount Free Gift Card Label',
    'qr_code_payment_discount_free_gift_card_seal': 'QR Code Payment Discount Free Gift Card Seal',
    'qr_code_payment_discount_free_gift_card_stamp': 'QR Code Payment Discount Free Gift Card Stamp',
    'qr_code_payment_discount_free_gift_card_envelope': 'QR Code Payment Discount Free Gift Card Envelope',
  };
  
  /// Get localized value for a key
  String translate(String key) {
    // Get the appropriate map based on locale
    final localizedValues = locale.languageCode == 'ar' 
        ? _localizedValuesAr 
        : _localizedValuesEn;
    
    // Return the localized value or the key itself if not found
    return localizedValues[key] ?? key;
  }
}

/// Delegate for AppLocalizations
class _AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return ['ar', 'en'].contains(locale.languageCode);
  }

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}

/// Extension method for easier access to localized strings
extension AppLocalizationsExtension on BuildContext {
  AppLocalizations get l10n => AppLocalizations.of(this);
  
  /// Translate a key
  String tr(String key) => AppLocalizations.of(this).translate(key);
}

/// A widget that provides localization to the app
class AppLocalizationsProvider extends StatelessWidget {
  final Widget child;
  final Locale locale;
  
  const AppLocalizationsProvider({
    Key? key,
    required this.child,
    required this.locale,
  }) : super(key: key);
  
  @override
  Widget build(BuildContext context) {
    return Localizations.override(
      context: context,
      locale: locale,
      delegates: const [
        AppLocalizations.delegate,
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
      ],
      child: child,
    );
  }
}
