name: Build Release APK

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  build_release_apk:
    name: Build Release APK
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable' # يمكنك تغييرها إلى إصدار محدد إذا لزم الأمر
          channel: 'stable'
          cache: true
          cache-key: flutter-stable-${{ hashFiles('pubspec.lock') }}
          cache-path: ${{ runner.tool_cache }}/flutter

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Check Flutter environment
        run: flutter doctor -v

      - name: Run tests
        run: flutter test

      - name: Build Release APK
        run: flutter build apk --release --split-per-abi

      - name: Upload Release APK
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/release/**/app-*.apk
          if-no-files-found: error
